// Code generated by protoc-gen-go. DO NOT EDIT.
// source: relayer.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeliverMeta struct {
	CurrHash             string   `protobuf:"bytes,1,opt,name=currHash,proto3" json:"currHash,omitempty"`
	Height               int64    `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeliverMeta) Reset()         { *m = DeliverMeta{} }
func (m *DeliverMeta) String() string { return proto.CompactTextString(m) }
func (*DeliverMeta) ProtoMessage()    {}
func (*DeliverMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_202a89775a80bd4c, []int{0}
}

func (m *DeliverMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeliverMeta.Unmarshal(m, b)
}
func (m *DeliverMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeliverMeta.Marshal(b, m, deterministic)
}
func (m *DeliverMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeliverMeta.Merge(m, src)
}
func (m *DeliverMeta) XXX_Size() int {
	return xxx_messageInfo_DeliverMeta.Size(m)
}
func (m *DeliverMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_DeliverMeta.DiscardUnknown(m)
}

var xxx_messageInfo_DeliverMeta proto.InternalMessageInfo

func (m *DeliverMeta) GetCurrHash() string {
	if m != nil {
		return m.CurrHash
	}
	return ""
}

func (m *DeliverMeta) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterType((*DeliverMeta)(nil), "pb.DeliverMeta")
}

func init() { proto.RegisterFile("relayer.proto", fileDescriptor_202a89775a80bd4c) }

var fileDescriptor_202a89775a80bd4c = []byte{
	// 103 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0xcd, 0x49,
	0xac, 0x4c, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x72, 0xe4,
	0xe2, 0x76, 0x49, 0xcd, 0xc9, 0x2c, 0x4b, 0x2d, 0xf2, 0x4d, 0x2d, 0x49, 0x14, 0x92, 0xe2, 0xe2,
	0x48, 0x2e, 0x2d, 0x2a, 0xf2, 0x48, 0x2c, 0xce, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82,
	0xf3, 0x85, 0xc4, 0xb8, 0xd8, 0x32, 0x52, 0x33, 0xd3, 0x33, 0x4a, 0x24, 0x98, 0x14, 0x18, 0x35,
	0x98, 0x83, 0xa0, 0xbc, 0x24, 0x36, 0xb0, 0x69, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc6,
	0xe5, 0xcc, 0xf7, 0x5e, 0x00, 0x00, 0x00,
}
