// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package xuperp2p

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type XuperMessage_MessageType int32

const (
	XuperMessage_SENDBLOCK                XuperMessage_MessageType = 0
	XuperMessage_POSTTX                   XuperMessage_MessageType = 1
	XuperMessage_BATCHPOSTTX              XuperMessage_MessageType = 2
	XuperMessage_GET_BLOCK                XuperMessage_MessageType = 3
	XuperMessage_PING                     XuperMessage_MessageType = 4
	XuperMessage_GET_BLOCKCHAINSTATUS     XuperMessage_MessageType = 5
	XuperMessage_GET_BLOCK_RES            XuperMessage_MessageType = 6
	XuperMessage_GET_BLOCKCHAINSTATUS_RES XuperMessage_MessageType = 7
	// 向邻近确认区块是否为最新状态区块
	XuperMessage_CONFIRM_BLOCKCHAINSTATUS     XuperMessage_MessageType = 8
	XuperMessage_CONFIRM_BLOCKCHAINSTATUS_RES XuperMessage_MessageType = 9
	XuperMessage_MSG_TYPE_NONE                XuperMessage_MessageType = 10
	// query RPC port information
	XuperMessage_GET_RPC_PORT     XuperMessage_MessageType = 11
	XuperMessage_GET_RPC_PORT_RES XuperMessage_MessageType = 12
	// get authentication information
	XuperMessage_GET_AUTHENTICATION     XuperMessage_MessageType = 13
	XuperMessage_GET_AUTHENTICATION_RES XuperMessage_MessageType = 14
	// chained-bft NEW_VIEW message
	XuperMessage_CHAINED_BFT_NEW_VIEW_MSG XuperMessage_MessageType = 15
	// chained-bft NEW_PROPOSAL message
	XuperMessage_CHAINED_BFT_NEW_PROPOSAL_MSG XuperMessage_MessageType = 16
	// chained-bft vote message
	XuperMessage_CHAINED_BFT_VOTE_MSG XuperMessage_MessageType = 17
)

var XuperMessage_MessageType_name = map[int32]string{
	0:  "SENDBLOCK",
	1:  "POSTTX",
	2:  "BATCHPOSTTX",
	3:  "GET_BLOCK",
	4:  "PING",
	5:  "GET_BLOCKCHAINSTATUS",
	6:  "GET_BLOCK_RES",
	7:  "GET_BLOCKCHAINSTATUS_RES",
	8:  "CONFIRM_BLOCKCHAINSTATUS",
	9:  "CONFIRM_BLOCKCHAINSTATUS_RES",
	10: "MSG_TYPE_NONE",
	11: "GET_RPC_PORT",
	12: "GET_RPC_PORT_RES",
	13: "GET_AUTHENTICATION",
	14: "GET_AUTHENTICATION_RES",
	15: "CHAINED_BFT_NEW_VIEW_MSG",
	16: "CHAINED_BFT_NEW_PROPOSAL_MSG",
	17: "CHAINED_BFT_VOTE_MSG",
}

var XuperMessage_MessageType_value = map[string]int32{
	"SENDBLOCK":                    0,
	"POSTTX":                       1,
	"BATCHPOSTTX":                  2,
	"GET_BLOCK":                    3,
	"PING":                         4,
	"GET_BLOCKCHAINSTATUS":         5,
	"GET_BLOCK_RES":                6,
	"GET_BLOCKCHAINSTATUS_RES":     7,
	"CONFIRM_BLOCKCHAINSTATUS":     8,
	"CONFIRM_BLOCKCHAINSTATUS_RES": 9,
	"MSG_TYPE_NONE":                10,
	"GET_RPC_PORT":                 11,
	"GET_RPC_PORT_RES":             12,
	"GET_AUTHENTICATION":           13,
	"GET_AUTHENTICATION_RES":       14,
	"CHAINED_BFT_NEW_VIEW_MSG":     15,
	"CHAINED_BFT_NEW_PROPOSAL_MSG": 16,
	"CHAINED_BFT_VOTE_MSG":         17,
}

func (x XuperMessage_MessageType) String() string {
	return proto.EnumName(XuperMessage_MessageType_name, int32(x))
}

func (XuperMessage_MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type XuperMessage_ErrorType int32

const (
	// success
	XuperMessage_SUCCESS XuperMessage_ErrorType = 0
	XuperMessage_NONE    XuperMessage_ErrorType = 1
	// common error
	XuperMessage_UNKNOW_ERROR             XuperMessage_ErrorType = 2
	XuperMessage_CHECK_SUM_ERROR          XuperMessage_ErrorType = 3
	XuperMessage_UNMARSHAL_MSG_BODY_ERROR XuperMessage_ErrorType = 4
	XuperMessage_CONNECT_REFUSE           XuperMessage_ErrorType = 5
	// block error
	XuperMessage_GET_BLOCKCHAIN_ERROR           XuperMessage_ErrorType = 6
	XuperMessage_BLOCKCHAIN_NOTEXIST            XuperMessage_ErrorType = 7
	XuperMessage_GET_BLOCK_ERROR                XuperMessage_ErrorType = 8
	XuperMessage_CONFIRM_BLOCKCHAINSTATUS_ERROR XuperMessage_ErrorType = 9
	XuperMessage_GET_AUTHENTICATION_ERROR       XuperMessage_ErrorType = 10
	XuperMessage_GET_AUTHENTICATION_NOT_PASS    XuperMessage_ErrorType = 11
)

var XuperMessage_ErrorType_name = map[int32]string{
	0:  "SUCCESS",
	1:  "NONE",
	2:  "UNKNOW_ERROR",
	3:  "CHECK_SUM_ERROR",
	4:  "UNMARSHAL_MSG_BODY_ERROR",
	5:  "CONNECT_REFUSE",
	6:  "GET_BLOCKCHAIN_ERROR",
	7:  "BLOCKCHAIN_NOTEXIST",
	8:  "GET_BLOCK_ERROR",
	9:  "CONFIRM_BLOCKCHAINSTATUS_ERROR",
	10: "GET_AUTHENTICATION_ERROR",
	11: "GET_AUTHENTICATION_NOT_PASS",
}

var XuperMessage_ErrorType_value = map[string]int32{
	"SUCCESS":                        0,
	"NONE":                           1,
	"UNKNOW_ERROR":                   2,
	"CHECK_SUM_ERROR":                3,
	"UNMARSHAL_MSG_BODY_ERROR":       4,
	"CONNECT_REFUSE":                 5,
	"GET_BLOCKCHAIN_ERROR":           6,
	"BLOCKCHAIN_NOTEXIST":            7,
	"GET_BLOCK_ERROR":                8,
	"CONFIRM_BLOCKCHAINSTATUS_ERROR": 9,
	"GET_AUTHENTICATION_ERROR":       10,
	"GET_AUTHENTICATION_NOT_PASS":    11,
}

func (x XuperMessage_ErrorType) String() string {
	return proto.EnumName(XuperMessage_ErrorType_name, int32(x))
}

func (XuperMessage_ErrorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 1}
}

// XuperMessage is the message of Xuper p2p server
type XuperMessage struct {
	Header               *XuperMessage_MessageHeader `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Data                 *XuperMessage_MessageData   `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *XuperMessage) Reset()         { *m = XuperMessage{} }
func (m *XuperMessage) String() string { return proto.CompactTextString(m) }
func (*XuperMessage) ProtoMessage()    {}
func (*XuperMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *XuperMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XuperMessage.Unmarshal(m, b)
}
func (m *XuperMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XuperMessage.Marshal(b, m, deterministic)
}
func (m *XuperMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XuperMessage.Merge(m, src)
}
func (m *XuperMessage) XXX_Size() int {
	return xxx_messageInfo_XuperMessage.Size(m)
}
func (m *XuperMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_XuperMessage.DiscardUnknown(m)
}

var xxx_messageInfo_XuperMessage proto.InternalMessageInfo

func (m *XuperMessage) GetHeader() *XuperMessage_MessageHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *XuperMessage) GetData() *XuperMessage_MessageData {
	if m != nil {
		return m.Data
	}
	return nil
}

// MessageHeader is the message header of Xuper p2p server
type XuperMessage_MessageHeader struct {
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// dataCheckSum is the message data checksum, it can be used check where the message have been received
	Logid                string                   `protobuf:"bytes,2,opt,name=logid,proto3" json:"logid,omitempty"`
	From                 string                   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Bcname               string                   `protobuf:"bytes,4,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Type                 XuperMessage_MessageType `protobuf:"varint,5,opt,name=type,proto3,enum=xuperp2p.XuperMessage_MessageType" json:"type,omitempty"`
	DataCheckSum         uint32                   `protobuf:"varint,6,opt,name=dataCheckSum,proto3" json:"dataCheckSum,omitempty"`
	ErrorType            XuperMessage_ErrorType   `protobuf:"varint,7,opt,name=errorType,proto3,enum=xuperp2p.XuperMessage_ErrorType" json:"errorType,omitempty"`
	Compressed           bool                     `protobuf:"varint,8,opt,name=compressed,proto3" json:"compressed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *XuperMessage_MessageHeader) Reset()         { *m = XuperMessage_MessageHeader{} }
func (m *XuperMessage_MessageHeader) String() string { return proto.CompactTextString(m) }
func (*XuperMessage_MessageHeader) ProtoMessage()    {}
func (*XuperMessage_MessageHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

func (m *XuperMessage_MessageHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XuperMessage_MessageHeader.Unmarshal(m, b)
}
func (m *XuperMessage_MessageHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XuperMessage_MessageHeader.Marshal(b, m, deterministic)
}
func (m *XuperMessage_MessageHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XuperMessage_MessageHeader.Merge(m, src)
}
func (m *XuperMessage_MessageHeader) XXX_Size() int {
	return xxx_messageInfo_XuperMessage_MessageHeader.Size(m)
}
func (m *XuperMessage_MessageHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_XuperMessage_MessageHeader.DiscardUnknown(m)
}

var xxx_messageInfo_XuperMessage_MessageHeader proto.InternalMessageInfo

func (m *XuperMessage_MessageHeader) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *XuperMessage_MessageHeader) GetLogid() string {
	if m != nil {
		return m.Logid
	}
	return ""
}

func (m *XuperMessage_MessageHeader) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *XuperMessage_MessageHeader) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *XuperMessage_MessageHeader) GetType() XuperMessage_MessageType {
	if m != nil {
		return m.Type
	}
	return XuperMessage_SENDBLOCK
}

func (m *XuperMessage_MessageHeader) GetDataCheckSum() uint32 {
	if m != nil {
		return m.DataCheckSum
	}
	return 0
}

func (m *XuperMessage_MessageHeader) GetErrorType() XuperMessage_ErrorType {
	if m != nil {
		return m.ErrorType
	}
	return XuperMessage_SUCCESS
}

func (m *XuperMessage_MessageHeader) GetCompressed() bool {
	if m != nil {
		return m.Compressed
	}
	return false
}

// MessageData is the message data of Xuper p2p server
type XuperMessage_MessageData struct {
	// msgInfo is the message infomation, use protobuf coding style
	MsgInfo              []byte   `protobuf:"bytes,3,opt,name=msgInfo,proto3" json:"msgInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XuperMessage_MessageData) Reset()         { *m = XuperMessage_MessageData{} }
func (m *XuperMessage_MessageData) String() string { return proto.CompactTextString(m) }
func (*XuperMessage_MessageData) ProtoMessage()    {}
func (*XuperMessage_MessageData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 1}
}

func (m *XuperMessage_MessageData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XuperMessage_MessageData.Unmarshal(m, b)
}
func (m *XuperMessage_MessageData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XuperMessage_MessageData.Marshal(b, m, deterministic)
}
func (m *XuperMessage_MessageData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XuperMessage_MessageData.Merge(m, src)
}
func (m *XuperMessage_MessageData) XXX_Size() int {
	return xxx_messageInfo_XuperMessage_MessageData.Size(m)
}
func (m *XuperMessage_MessageData) XXX_DiscardUnknown() {
	xxx_messageInfo_XuperMessage_MessageData.DiscardUnknown(m)
}

var xxx_messageInfo_XuperMessage_MessageData proto.InternalMessageInfo

func (m *XuperMessage_MessageData) GetMsgInfo() []byte {
	if m != nil {
		return m.MsgInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("xuperp2p.XuperMessage_MessageType", XuperMessage_MessageType_name, XuperMessage_MessageType_value)
	proto.RegisterEnum("xuperp2p.XuperMessage_ErrorType", XuperMessage_ErrorType_name, XuperMessage_ErrorType_value)
	proto.RegisterType((*XuperMessage)(nil), "xuperp2p.XuperMessage")
	proto.RegisterType((*XuperMessage_MessageHeader)(nil), "xuperp2p.XuperMessage.MessageHeader")
	proto.RegisterType((*XuperMessage_MessageData)(nil), "xuperp2p.XuperMessage.MessageData")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 635 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0x5d, 0x4f, 0xdb, 0x3e,
	0x14, 0xc6, 0xe9, 0x7b, 0x73, 0xda, 0x82, 0x39, 0x20, 0xfe, 0x11, 0x7f, 0xc4, 0xaa, 0x6a, 0xd2,
	0x7a, 0xd5, 0x0b, 0x26, 0xed, 0x6a, 0x9a, 0x94, 0xa6, 0xa6, 0x8d, 0xa0, 0x76, 0x64, 0xbb, 0xbc,
	0x5c, 0x45, 0x85, 0x06, 0x86, 0xb6, 0x92, 0x28, 0x2d, 0xd3, 0xf8, 0x42, 0x4c, 0xfb, 0x96, 0x93,
	0x9d, 0xb4, 0x94, 0xb7, 0xed, 0x0a, 0xce, 0xf3, 0xfc, 0x1e, 0x9f, 0xe3, 0xe3, 0xa8, 0xd0, 0x98,
	0x86, 0xb3, 0xd9, 0xf8, 0x3a, 0xec, 0xc4, 0x49, 0x34, 0x8f, 0xb0, 0xfa, 0xf3, 0x2e, 0x0e, 0x93,
	0xf8, 0x20, 0x6e, 0xfd, 0xb6, 0xa0, 0x7e, 0xa6, 0x8b, 0x61, 0x0a, 0xe0, 0x67, 0x28, 0x0f, 0xc2,
	0xf1, 0x24, 0x4c, 0xec, 0x5c, 0x33, 0xd7, 0xae, 0x1d, 0xbc, 0xef, 0x2c, 0xd8, 0xce, 0x2a, 0xd7,
	0xc9, 0xfe, 0xa6, 0xac, 0xc8, 0x32, 0xf8, 0x09, 0x8a, 0xbd, 0xf1, 0x7c, 0x6c, 0xe7, 0x4d, 0xb6,
	0xf5, 0xf7, 0xac, 0x26, 0x85, 0xe1, 0x77, 0x7f, 0xe5, 0xa1, 0xf1, 0xe4, 0x44, 0xb4, 0xa1, 0xf2,
	0x23, 0x4c, 0x66, 0x37, 0xd1, 0xad, 0x19, 0xc4, 0x12, 0x8b, 0x12, 0xb7, 0xa1, 0xf4, 0x3d, 0xba,
	0xbe, 0x99, 0x98, 0x26, 0x96, 0x48, 0x0b, 0x44, 0x28, 0x5e, 0x25, 0xd1, 0xd4, 0x2e, 0x18, 0xd1,
	0xfc, 0x8f, 0x3b, 0x50, 0xbe, 0xb8, 0xbc, 0x1d, 0x4f, 0x43, 0xbb, 0x68, 0xd4, 0xac, 0xd2, 0x53,
	0xce, 0xef, 0xe3, 0xd0, 0x2e, 0x35, 0x73, 0xed, 0xf5, 0x7f, 0x4d, 0xa9, 0xee, 0xe3, 0x50, 0x18,
	0x1e, 0x5b, 0x50, 0x9f, 0x8c, 0xe7, 0x63, 0xf7, 0x6b, 0x78, 0xf9, 0x4d, 0xde, 0x4d, 0xed, 0x72,
	0x33, 0xd7, 0x6e, 0x88, 0x27, 0x1a, 0x7e, 0x01, 0x2b, 0x4c, 0x92, 0x28, 0xd1, 0x31, 0xbb, 0x62,
	0x1a, 0x34, 0xdf, 0x68, 0x40, 0x17, 0x9c, 0x78, 0x8c, 0xe0, 0x3e, 0xc0, 0x65, 0x34, 0x8d, 0x93,
	0x70, 0x36, 0x0b, 0x27, 0x76, 0xb5, 0x99, 0x6b, 0x57, 0xc5, 0x8a, 0xb2, 0xfb, 0x01, 0x6a, 0x2b,
	0xeb, 0xd3, 0x6b, 0x9a, 0xce, 0xae, 0xbd, 0xdb, 0xab, 0xc8, 0xdc, 0xbc, 0x2e, 0x16, 0x65, 0xeb,
	0xa1, 0xb0, 0x24, 0xcd, 0xc1, 0x0d, 0xb0, 0x24, 0x65, 0xbd, 0xee, 0x31, 0x77, 0x8f, 0xc8, 0x1a,
	0x02, 0x94, 0x7d, 0x2e, 0x95, 0x3a, 0x23, 0x39, 0xdc, 0x80, 0x5a, 0xd7, 0x51, 0xee, 0x20, 0x13,
	0xf2, 0x9a, 0xed, 0x53, 0x15, 0xa4, 0x6c, 0x01, 0xab, 0x50, 0xf4, 0x3d, 0xd6, 0x27, 0x45, 0xb4,
	0x61, 0x7b, 0x69, 0xb8, 0x03, 0xc7, 0x63, 0x52, 0x39, 0x6a, 0x24, 0x49, 0x09, 0x37, 0xa1, 0xb1,
	0x74, 0x02, 0x41, 0x25, 0x29, 0xe3, 0x1e, 0xd8, 0xaf, 0xc1, 0xc6, 0xad, 0x68, 0xd7, 0xe5, 0xec,
	0xd0, 0x13, 0xc3, 0x97, 0xc7, 0x55, 0xb1, 0x09, 0x7b, 0x6f, 0xb9, 0x26, 0x6f, 0xe9, 0x86, 0x43,
	0xd9, 0x0f, 0xd4, 0xb9, 0x4f, 0x03, 0xc6, 0x19, 0x25, 0x80, 0x04, 0xea, 0xba, 0xa1, 0xf0, 0xdd,
	0xc0, 0xe7, 0x42, 0x91, 0x1a, 0x6e, 0x03, 0x59, 0x55, 0x4c, 0xb4, 0x8e, 0x3b, 0x80, 0x5a, 0x75,
	0x46, 0x6a, 0x40, 0x99, 0xf2, 0x5c, 0x47, 0x79, 0x9c, 0x91, 0x06, 0xee, 0xc2, 0xce, 0x4b, 0xdd,
	0x64, 0xd6, 0xcd, 0xb8, 0x7a, 0x06, 0xda, 0x0b, 0xba, 0x87, 0x2a, 0x60, 0xf4, 0x34, 0x38, 0xf1,
	0xe8, 0x69, 0x30, 0x94, 0x7d, 0xb2, 0x61, 0xc6, 0x7d, 0xe6, 0xfa, 0x82, 0xfb, 0x5c, 0x3a, 0xc7,
	0x86, 0x20, 0x7a, 0x73, 0xab, 0xc4, 0x09, 0x57, 0xd4, 0x38, 0x9b, 0xad, 0x87, 0x3c, 0x58, 0xcb,
	0x4f, 0x01, 0x6b, 0x50, 0x91, 0x23, 0xd7, 0xa5, 0x52, 0x92, 0x35, 0xbd, 0x78, 0x73, 0xb5, 0x9c,
	0xbe, 0xda, 0x88, 0x1d, 0x31, 0x7e, 0x1a, 0x50, 0x21, 0xb8, 0x20, 0x79, 0xdc, 0x82, 0x0d, 0x77,
	0x40, 0xdd, 0xa3, 0x40, 0x8e, 0x86, 0x99, 0x58, 0xd0, 0x53, 0x8e, 0xd8, 0xd0, 0x11, 0x72, 0x90,
	0x36, 0x0e, 0xba, 0xbc, 0x77, 0x9e, 0xb9, 0x45, 0x44, 0x58, 0x77, 0x39, 0x63, 0xd4, 0xd5, 0x8b,
	0x38, 0x1c, 0x49, 0x4a, 0x4a, 0x2f, 0x5f, 0x34, 0xa3, 0xcb, 0xf8, 0x1f, 0x6c, 0xad, 0xa8, 0x8c,
	0x2b, 0x7a, 0xe6, 0x49, 0x45, 0x2a, 0xba, 0xf3, 0xe3, 0x53, 0xa7, 0x74, 0x15, 0x5b, 0xb0, 0xff,
	0xe6, 0x83, 0xa5, 0x8c, 0xb5, 0xf8, 0x20, 0x9e, 0xed, 0x37, 0x75, 0x01, 0xdf, 0xc1, 0xff, 0xaf,
	0xb8, 0x8c, 0xab, 0xc0, 0x77, 0xa4, 0x24, 0xb5, 0x8b, 0xb2, 0xf9, 0xf1, 0xfa, 0xf8, 0x27, 0x00,
	0x00, 0xff, 0xff, 0xc3, 0xd5, 0xbb, 0x5f, 0xcd, 0x04, 0x00, 0x00,
}
