// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// BlockStatus block status
type BlockStatus int32

const (
	BlockStatus_ERROR    BlockStatus = 0
	BlockStatus_TRUNK    BlockStatus = 1
	BlockStatus_BRANCH   BlockStatus = 2
	BlockStatus_NONEXIST BlockStatus = 3
)

var BlockStatus_name = map[int32]string{
	0: "ERROR",
	1: "TRUNK",
	2: "BRANCH",
	3: "NONEXIST",
}

var BlockStatus_value = map[string]int32{
	"ERROR":    0,
	"TRUNK":    1,
	"BRANCH":   2,
	"NONEXIST": 3,
}

func (x BlockStatus) String() string {
	return proto.EnumName(BlockStatus_name, int32(x))
}

func (BlockStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

///// EventType 事件类型
type EventType int32

const (
	EventType_UNDEFINED   EventType = 0
	EventType_BLOCK       EventType = 1
	EventType_TRANSACTION EventType = 2
	EventType_ACCOUNT     EventType = 3
)

var EventType_name = map[int32]string{
	0: "UNDEFINED",
	1: "BLOCK",
	2: "TRANSACTION",
	3: "ACCOUNT",
}

var EventType_value = map[string]int32{
	"UNDEFINED":   0,
	"BLOCK":       1,
	"TRANSACTION": 2,
	"ACCOUNT":     3,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}

func (EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

type UnSubscribeStatusInfo int32

const (
	UnSubscribeStatusInfo_UNSUBSCRIBE_UNDEFINED UnSubscribeStatusInfo = 0
	UnSubscribeStatusInfo_UNSUBSCRIBE_SUCCESS   UnSubscribeStatusInfo = 1
	UnSubscribeStatusInfo_UNSUBSCRIBE_FAILED    UnSubscribeStatusInfo = 2
)

var UnSubscribeStatusInfo_name = map[int32]string{
	0: "UNSUBSCRIBE_UNDEFINED",
	1: "UNSUBSCRIBE_SUCCESS",
	2: "UNSUBSCRIBE_FAILED",
}

var UnSubscribeStatusInfo_value = map[string]int32{
	"UNSUBSCRIBE_UNDEFINED": 0,
	"UNSUBSCRIBE_SUCCESS":   1,
	"UNSUBSCRIBE_FAILED":    2,
}

func (x UnSubscribeStatusInfo) String() string {
	return proto.EnumName(UnSubscribeStatusInfo_name, int32(x))
}

func (UnSubscribeStatusInfo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

// BlockStatusInfo 区块元数据
type BlockStatusInfo struct {
	Bcname               string      `protobuf:"bytes,1,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Status               BlockStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pb.BlockStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BlockStatusInfo) Reset()         { *m = BlockStatusInfo{} }
func (m *BlockStatusInfo) String() string { return proto.CompactTextString(m) }
func (*BlockStatusInfo) ProtoMessage()    {}
func (*BlockStatusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{0}
}

func (m *BlockStatusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockStatusInfo.Unmarshal(m, b)
}
func (m *BlockStatusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockStatusInfo.Marshal(b, m, deterministic)
}
func (m *BlockStatusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockStatusInfo.Merge(m, src)
}
func (m *BlockStatusInfo) XXX_Size() int {
	return xxx_messageInfo_BlockStatusInfo.Size(m)
}
func (m *BlockStatusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockStatusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BlockStatusInfo proto.InternalMessageInfo

func (m *BlockStatusInfo) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *BlockStatusInfo) GetStatus() BlockStatus {
	if m != nil {
		return m.Status
	}
	return BlockStatus_ERROR
}

type TransactionStatusInfo struct {
	Bcname               string            `protobuf:"bytes,1,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Initiator            string            `protobuf:"bytes,2,opt,name=initiator,proto3" json:"initiator,omitempty"`
	Status               TransactionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pb.TransactionStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *TransactionStatusInfo) Reset()         { *m = TransactionStatusInfo{} }
func (m *TransactionStatusInfo) String() string { return proto.CompactTextString(m) }
func (*TransactionStatusInfo) ProtoMessage()    {}
func (*TransactionStatusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{1}
}

func (m *TransactionStatusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionStatusInfo.Unmarshal(m, b)
}
func (m *TransactionStatusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionStatusInfo.Marshal(b, m, deterministic)
}
func (m *TransactionStatusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionStatusInfo.Merge(m, src)
}
func (m *TransactionStatusInfo) XXX_Size() int {
	return xxx_messageInfo_TransactionStatusInfo.Size(m)
}
func (m *TransactionStatusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionStatusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionStatusInfo proto.InternalMessageInfo

func (m *TransactionStatusInfo) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *TransactionStatusInfo) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *TransactionStatusInfo) GetStatus() TransactionStatus {
	if m != nil {
		return m.Status
	}
	return TransactionStatus_UNDEFINE
}

type AccountStatusInfo struct {
	Bcname               string            `protobuf:"bytes,1,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Status               TransactionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pb.TransactionStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AccountStatusInfo) Reset()         { *m = AccountStatusInfo{} }
func (m *AccountStatusInfo) String() string { return proto.CompactTextString(m) }
func (*AccountStatusInfo) ProtoMessage()    {}
func (*AccountStatusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{2}
}

func (m *AccountStatusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountStatusInfo.Unmarshal(m, b)
}
func (m *AccountStatusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountStatusInfo.Marshal(b, m, deterministic)
}
func (m *AccountStatusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountStatusInfo.Merge(m, src)
}
func (m *AccountStatusInfo) XXX_Size() int {
	return xxx_messageInfo_AccountStatusInfo.Size(m)
}
func (m *AccountStatusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountStatusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountStatusInfo proto.InternalMessageInfo

func (m *AccountStatusInfo) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *AccountStatusInfo) GetStatus() TransactionStatus {
	if m != nil {
		return m.Status
	}
	return TransactionStatus_UNDEFINE
}

/////// 事件订阅请求数据结构
// EventRequest 将事件订阅统一归为EventRequest
type EventRequest struct {
	Type                 EventType `protobuf:"varint,1,opt,name=type,proto3,enum=pb.EventType" json:"type,omitempty"`
	Payload              []byte    `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EventRequest) Reset()         { *m = EventRequest{} }
func (m *EventRequest) String() string { return proto.CompactTextString(m) }
func (*EventRequest) ProtoMessage()    {}
func (*EventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{3}
}

func (m *EventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventRequest.Unmarshal(m, b)
}
func (m *EventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventRequest.Marshal(b, m, deterministic)
}
func (m *EventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRequest.Merge(m, src)
}
func (m *EventRequest) XXX_Size() int {
	return xxx_messageInfo_EventRequest.Size(m)
}
func (m *EventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EventRequest proto.InternalMessageInfo

func (m *EventRequest) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_UNDEFINED
}

func (m *EventRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// BlockEventRequest 订阅区块请求
type BlockEventRequest struct {
	Bcname               string   `protobuf:"bytes,1,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Proposer             string   `protobuf:"bytes,2,opt,name=proposer,proto3" json:"proposer,omitempty"`
	StartHeight          int64    `protobuf:"varint,3,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	EndHeight            int64    `protobuf:"varint,4,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	NeedContent          bool     `protobuf:"varint,5,opt,name=need_content,json=needContent,proto3" json:"need_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockEventRequest) Reset()         { *m = BlockEventRequest{} }
func (m *BlockEventRequest) String() string { return proto.CompactTextString(m) }
func (*BlockEventRequest) ProtoMessage()    {}
func (*BlockEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{4}
}

func (m *BlockEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockEventRequest.Unmarshal(m, b)
}
func (m *BlockEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockEventRequest.Marshal(b, m, deterministic)
}
func (m *BlockEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockEventRequest.Merge(m, src)
}
func (m *BlockEventRequest) XXX_Size() int {
	return xxx_messageInfo_BlockEventRequest.Size(m)
}
func (m *BlockEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockEventRequest proto.InternalMessageInfo

func (m *BlockEventRequest) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *BlockEventRequest) GetProposer() string {
	if m != nil {
		return m.Proposer
	}
	return ""
}

func (m *BlockEventRequest) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *BlockEventRequest) GetEndHeight() int64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *BlockEventRequest) GetNeedContent() bool {
	if m != nil {
		return m.NeedContent
	}
	return false
}

// TransactionEventRequest 订阅交易请求
type TransactionEventRequest struct {
	Bcname               string   `protobuf:"bytes,1,opt,name=bcname,proto3" json:"bcname,omitempty"`
	Initiator            string   `protobuf:"bytes,2,opt,name=initiator,proto3" json:"initiator,omitempty"`
	AuthRequire          []string `protobuf:"bytes,3,rep,name=auth_require,json=authRequire,proto3" json:"auth_require,omitempty"`
	NeedContent          bool     `protobuf:"varint,4,opt,name=need_content,json=needContent,proto3" json:"need_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionEventRequest) Reset()         { *m = TransactionEventRequest{} }
func (m *TransactionEventRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionEventRequest) ProtoMessage()    {}
func (*TransactionEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{5}
}

func (m *TransactionEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEventRequest.Unmarshal(m, b)
}
func (m *TransactionEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEventRequest.Marshal(b, m, deterministic)
}
func (m *TransactionEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEventRequest.Merge(m, src)
}
func (m *TransactionEventRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionEventRequest.Size(m)
}
func (m *TransactionEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEventRequest proto.InternalMessageInfo

func (m *TransactionEventRequest) GetBcname() string {
	if m != nil {
		return m.Bcname
	}
	return ""
}

func (m *TransactionEventRequest) GetInitiator() string {
	if m != nil {
		return m.Initiator
	}
	return ""
}

func (m *TransactionEventRequest) GetAuthRequire() []string {
	if m != nil {
		return m.AuthRequire
	}
	return nil
}

func (m *TransactionEventRequest) GetNeedContent() bool {
	if m != nil {
		return m.NeedContent
	}
	return false
}

// AccountEventRequest 订阅账户请求
type AccountEventRequest struct {
	FromAddr             string   `protobuf:"bytes,1,opt,name=from_addr,json=fromAddr,proto3" json:"from_addr,omitempty"`
	ToAddr               string   `protobuf:"bytes,2,opt,name=to_addr,json=toAddr,proto3" json:"to_addr,omitempty"`
	NeedContent          bool     `protobuf:"varint,3,opt,name=need_content,json=needContent,proto3" json:"need_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountEventRequest) Reset()         { *m = AccountEventRequest{} }
func (m *AccountEventRequest) String() string { return proto.CompactTextString(m) }
func (*AccountEventRequest) ProtoMessage()    {}
func (*AccountEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{6}
}

func (m *AccountEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountEventRequest.Unmarshal(m, b)
}
func (m *AccountEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountEventRequest.Marshal(b, m, deterministic)
}
func (m *AccountEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountEventRequest.Merge(m, src)
}
func (m *AccountEventRequest) XXX_Size() int {
	return xxx_messageInfo_AccountEventRequest.Size(m)
}
func (m *AccountEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountEventRequest proto.InternalMessageInfo

func (m *AccountEventRequest) GetFromAddr() string {
	if m != nil {
		return m.FromAddr
	}
	return ""
}

func (m *AccountEventRequest) GetToAddr() string {
	if m != nil {
		return m.ToAddr
	}
	return ""
}

func (m *AccountEventRequest) GetNeedContent() bool {
	if m != nil {
		return m.NeedContent
	}
	return false
}

// UnSubscribeRequest 取消事件订阅请求
type UnSubscribeRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnSubscribeRequest) Reset()         { *m = UnSubscribeRequest{} }
func (m *UnSubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnSubscribeRequest) ProtoMessage()    {}
func (*UnSubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{7}
}

func (m *UnSubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnSubscribeRequest.Unmarshal(m, b)
}
func (m *UnSubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnSubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnSubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnSubscribeRequest.Merge(m, src)
}
func (m *UnSubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnSubscribeRequest.Size(m)
}
func (m *UnSubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnSubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnSubscribeRequest proto.InternalMessageInfo

func (m *UnSubscribeRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

//////// 事件订阅返回数据结构
/////// UnSubscribeResponse 取消订阅pb接口
type UnSubscribeResponse struct {
	Id                   string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               UnSubscribeStatusInfo `protobuf:"varint,3,opt,name=status,proto3,enum=pb.UnSubscribeStatusInfo" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UnSubscribeResponse) Reset()         { *m = UnSubscribeResponse{} }
func (m *UnSubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*UnSubscribeResponse) ProtoMessage()    {}
func (*UnSubscribeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{8}
}

func (m *UnSubscribeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnSubscribeResponse.Unmarshal(m, b)
}
func (m *UnSubscribeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnSubscribeResponse.Marshal(b, m, deterministic)
}
func (m *UnSubscribeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnSubscribeResponse.Merge(m, src)
}
func (m *UnSubscribeResponse) XXX_Size() int {
	return xxx_messageInfo_UnSubscribeResponse.Size(m)
}
func (m *UnSubscribeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnSubscribeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnSubscribeResponse proto.InternalMessageInfo

func (m *UnSubscribeResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UnSubscribeResponse) GetStatus() UnSubscribeStatusInfo {
	if m != nil {
		return m.Status
	}
	return UnSubscribeStatusInfo_UNSUBSCRIBE_UNDEFINED
}

///// Event 将多种事件订阅回复统一为Event, 易于扩展
type Event struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 EventType `protobuf:"varint,2,opt,name=type,proto3,enum=pb.EventType" json:"type,omitempty"`
	Payload              []byte    `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{9}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Event) GetType() EventType {
	if m != nil {
		return m.Type
	}
	return EventType_UNDEFINED
}

func (m *Event) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// SubscribeEvent 订阅产生的event_id
type SubscribeEvent struct {
	Request              *EventRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SubscribeEvent) Reset()         { *m = SubscribeEvent{} }
func (m *SubscribeEvent) String() string { return proto.CompactTextString(m) }
func (*SubscribeEvent) ProtoMessage()    {}
func (*SubscribeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{10}
}

func (m *SubscribeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeEvent.Unmarshal(m, b)
}
func (m *SubscribeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeEvent.Marshal(b, m, deterministic)
}
func (m *SubscribeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeEvent.Merge(m, src)
}
func (m *SubscribeEvent) XXX_Size() int {
	return xxx_messageInfo_SubscribeEvent.Size(m)
}
func (m *SubscribeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeEvent proto.InternalMessageInfo

func (m *SubscribeEvent) GetRequest() *EventRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

// BlockEvent 订阅区块返回
type BlockEvent struct {
	Status               *BlockStatusInfo `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Block                *InternalBlock   `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BlockEvent) Reset()         { *m = BlockEvent{} }
func (m *BlockEvent) String() string { return proto.CompactTextString(m) }
func (*BlockEvent) ProtoMessage()    {}
func (*BlockEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{11}
}

func (m *BlockEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockEvent.Unmarshal(m, b)
}
func (m *BlockEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockEvent.Marshal(b, m, deterministic)
}
func (m *BlockEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockEvent.Merge(m, src)
}
func (m *BlockEvent) XXX_Size() int {
	return xxx_messageInfo_BlockEvent.Size(m)
}
func (m *BlockEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockEvent.DiscardUnknown(m)
}

var xxx_messageInfo_BlockEvent proto.InternalMessageInfo

func (m *BlockEvent) GetStatus() *BlockStatusInfo {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *BlockEvent) GetBlock() *InternalBlock {
	if m != nil {
		return m.Block
	}
	return nil
}

// TransactionEvent 订阅交易返回
type TransactionEvent struct {
	Status               *TransactionStatusInfo `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Tx                   *Transaction           `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *TransactionEvent) Reset()         { *m = TransactionEvent{} }
func (m *TransactionEvent) String() string { return proto.CompactTextString(m) }
func (*TransactionEvent) ProtoMessage()    {}
func (*TransactionEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{12}
}

func (m *TransactionEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEvent.Unmarshal(m, b)
}
func (m *TransactionEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEvent.Marshal(b, m, deterministic)
}
func (m *TransactionEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEvent.Merge(m, src)
}
func (m *TransactionEvent) XXX_Size() int {
	return xxx_messageInfo_TransactionEvent.Size(m)
}
func (m *TransactionEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEvent.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEvent proto.InternalMessageInfo

func (m *TransactionEvent) GetStatus() *TransactionStatusInfo {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *TransactionEvent) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

// AccountEvent 订阅账户返回
type AccountEvent struct {
	Status               *AccountStatusInfo `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Tx                   *Transaction       `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AccountEvent) Reset()         { *m = AccountEvent{} }
func (m *AccountEvent) String() string { return proto.CompactTextString(m) }
func (*AccountEvent) ProtoMessage()    {}
func (*AccountEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_2d17a9d3f0ddf27e, []int{13}
}

func (m *AccountEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountEvent.Unmarshal(m, b)
}
func (m *AccountEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountEvent.Marshal(b, m, deterministic)
}
func (m *AccountEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountEvent.Merge(m, src)
}
func (m *AccountEvent) XXX_Size() int {
	return xxx_messageInfo_AccountEvent.Size(m)
}
func (m *AccountEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AccountEvent proto.InternalMessageInfo

func (m *AccountEvent) GetStatus() *AccountStatusInfo {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *AccountEvent) GetTx() *Transaction {
	if m != nil {
		return m.Tx
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.BlockStatus", BlockStatus_name, BlockStatus_value)
	proto.RegisterEnum("pb.EventType", EventType_name, EventType_value)
	proto.RegisterEnum("pb.UnSubscribeStatusInfo", UnSubscribeStatusInfo_name, UnSubscribeStatusInfo_value)
	proto.RegisterType((*BlockStatusInfo)(nil), "pb.BlockStatusInfo")
	proto.RegisterType((*TransactionStatusInfo)(nil), "pb.TransactionStatusInfo")
	proto.RegisterType((*AccountStatusInfo)(nil), "pb.AccountStatusInfo")
	proto.RegisterType((*EventRequest)(nil), "pb.EventRequest")
	proto.RegisterType((*BlockEventRequest)(nil), "pb.BlockEventRequest")
	proto.RegisterType((*TransactionEventRequest)(nil), "pb.TransactionEventRequest")
	proto.RegisterType((*AccountEventRequest)(nil), "pb.AccountEventRequest")
	proto.RegisterType((*UnSubscribeRequest)(nil), "pb.UnSubscribeRequest")
	proto.RegisterType((*UnSubscribeResponse)(nil), "pb.UnSubscribeResponse")
	proto.RegisterType((*Event)(nil), "pb.Event")
	proto.RegisterType((*SubscribeEvent)(nil), "pb.SubscribeEvent")
	proto.RegisterType((*BlockEvent)(nil), "pb.BlockEvent")
	proto.RegisterType((*TransactionEvent)(nil), "pb.TransactionEvent")
	proto.RegisterType((*AccountEvent)(nil), "pb.AccountEvent")
}

func init() { proto.RegisterFile("event.proto", fileDescriptor_2d17a9d3f0ddf27e) }

var fileDescriptor_2d17a9d3f0ddf27e = []byte{
	// 760 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0xc6, 0x4e, 0xf3, 0xe2, 0xb1, 0x9b, 0xb8, 0x1b, 0xa5, 0x49, 0x0b, 0x88, 0xc4, 0x42, 0xba,
	0x28, 0xe8, 0x2a, 0x08, 0x5f, 0x01, 0x29, 0x71, 0x7d, 0xba, 0xe8, 0x4e, 0x0e, 0x5a, 0x27, 0xd2,
	0x89, 0x0f, 0x44, 0x7e, 0xd9, 0x12, 0x8b, 0xde, 0xda, 0x67, 0xaf, 0xab, 0x56, 0xf0, 0x37, 0xf8,
	0x17, 0xfc, 0x48, 0xe4, 0xb5, 0xe3, 0x3a, 0x76, 0x81, 0x7c, 0x8b, 0x9f, 0x99, 0x79, 0x9e, 0x99,
	0xd9, 0x67, 0x37, 0x20, 0x93, 0x07, 0x42, 0xd9, 0x4d, 0x18, 0x05, 0x2c, 0x40, 0x62, 0xe8, 0x5c,
	0x2b, 0x8f, 0xee, 0xde, 0xf6, 0x69, 0x86, 0x68, 0x18, 0x7a, 0xcb, 0xfb, 0xc0, 0xfd, 0xdd, 0x62,
	0x36, 0x4b, 0xe2, 0x15, 0xbd, 0x0b, 0xd0, 0x25, 0xb4, 0x1c, 0x97, 0xda, 0x1f, 0xc9, 0x48, 0x18,
	0x0b, 0x53, 0x09, 0xe7, 0x5f, 0xe8, 0x15, 0xb4, 0x62, 0x9e, 0x35, 0x12, 0xc7, 0xc2, 0xb4, 0x3b,
	0xef, 0xdd, 0x84, 0xce, 0x4d, 0xa9, 0x18, 0xe7, 0x61, 0xed, 0x4f, 0x18, 0x6c, 0x22, 0x9b, 0xc6,
	0xb6, 0xcb, 0xfc, 0x80, 0x9e, 0xc0, 0xfc, 0x05, 0x48, 0x3e, 0xf5, 0x99, 0x6f, 0xb3, 0x20, 0xe2,
	0xe4, 0x12, 0x7e, 0x06, 0xd0, 0xeb, 0x42, 0xb7, 0xc1, 0x75, 0x07, 0xa9, 0x6e, 0x4d, 0xa0, 0x50,
	0xff, 0x05, 0x2e, 0x16, 0xae, 0x1b, 0x24, 0x94, 0x9d, 0xa0, 0xfc, 0xba, 0x32, 0xd3, 0xff, 0x70,
	0xbf, 0x03, 0xc5, 0x48, 0xd7, 0x89, 0xc9, 0xa7, 0x84, 0xc4, 0x0c, 0x4d, 0xe0, 0x8c, 0x3d, 0x85,
	0x19, 0x69, 0x77, 0x7e, 0x9e, 0x16, 0xf3, 0xf8, 0xe6, 0x29, 0x24, 0x98, 0x87, 0xd0, 0x08, 0xda,
	0xa1, 0xfd, 0x74, 0x1f, 0xd8, 0x1e, 0x97, 0x50, 0xf0, 0xe1, 0x53, 0xfb, 0x5b, 0x80, 0x0b, 0xbe,
	0xbe, 0x23, 0xca, 0x7f, 0xeb, 0xf4, 0x1a, 0x3a, 0x61, 0x14, 0x84, 0x41, 0x4c, 0x0e, 0x2b, 0x2a,
	0xbe, 0xd1, 0x04, 0x94, 0x98, 0xd9, 0x11, 0xdb, 0xed, 0x89, 0xff, 0xdb, 0x9e, 0xf1, 0x3d, 0x35,
	0xb0, 0xcc, 0xb1, 0xb7, 0x1c, 0x42, 0x5f, 0x02, 0x10, 0xea, 0x1d, 0x12, 0xce, 0x78, 0x82, 0x44,
	0xa8, 0x97, 0x87, 0x27, 0xa0, 0x50, 0x42, 0xbc, 0x9d, 0x1b, 0x50, 0x46, 0x28, 0x1b, 0x35, 0xc7,
	0xc2, 0xb4, 0x83, 0xe5, 0x14, 0xd3, 0x33, 0x48, 0xfb, 0x4b, 0x80, 0x61, 0x69, 0x33, 0x27, 0x35,
	0xfd, 0xdf, 0x07, 0x3b, 0x01, 0xc5, 0x4e, 0xd8, 0x7e, 0x17, 0x91, 0x4f, 0x89, 0x1f, 0x91, 0x51,
	0x63, 0xdc, 0x98, 0x4a, 0x58, 0x4e, 0x31, 0x9c, 0x41, 0xb5, 0xbe, 0xce, 0xea, 0x7d, 0x51, 0xe8,
	0xe7, 0xe7, 0x7d, 0xd4, 0xd2, 0xe7, 0x20, 0xdd, 0x45, 0xc1, 0xc7, 0x9d, 0xed, 0x79, 0x51, 0xde,
	0x55, 0x27, 0x05, 0x16, 0x9e, 0x17, 0xa1, 0x21, 0xb4, 0x59, 0x90, 0x85, 0xb2, 0xae, 0x5a, 0x2c,
	0xe0, 0x81, 0xaa, 0x5e, 0xa3, 0xae, 0xf7, 0x35, 0xa0, 0x2d, 0xb5, 0x12, 0x27, 0x76, 0x23, 0xdf,
	0x21, 0x07, 0xb9, 0x2e, 0x88, 0xbe, 0x97, 0xeb, 0x88, 0xbe, 0xa7, 0x7d, 0x80, 0xfe, 0x51, 0x56,
	0x1c, 0x06, 0x34, 0x26, 0xd5, 0x34, 0xf4, 0x5d, 0xc5, 0xdb, 0x57, 0xa9, 0x85, 0x4a, 0x85, 0xcf,
	0x16, 0x2e, 0x3c, 0xb8, 0x81, 0x26, 0x1f, 0xb4, 0xc6, 0x75, 0x30, 0xa3, 0x78, 0x92, 0x19, 0x1b,
	0xc7, 0x66, 0xfc, 0x01, 0xba, 0x85, 0x68, 0x46, 0x3f, 0x83, 0x76, 0x94, 0x0d, 0xc7, 0x35, 0xe4,
	0xb9, 0x5a, 0x30, 0xe6, 0x43, 0xe3, 0x43, 0x82, 0xe6, 0x00, 0x3c, 0x3b, 0x19, 0x7d, 0x53, 0x0c,
	0x95, 0x15, 0xf6, 0x2b, 0x0f, 0x45, 0x79, 0x1c, 0xf4, 0x0a, 0x9a, 0x4e, 0x1a, 0xe2, 0x6d, 0xcb,
	0xf3, 0x8b, 0x34, 0x77, 0x45, 0x19, 0x89, 0xa8, 0x7d, 0xcf, 0x6b, 0x70, 0x16, 0xd7, 0xee, 0x40,
	0xad, 0xda, 0xaf, 0xb4, 0xbe, 0x4c, 0xe9, 0xea, 0xc5, 0xeb, 0x7b, 0xa4, 0xf7, 0x15, 0x88, 0xec,
	0x31, 0x17, 0xeb, 0x55, 0xd2, 0xb1, 0xc8, 0x1e, 0xb5, 0x5f, 0x41, 0x29, 0xfb, 0xa9, 0xf4, 0x44,
	0x64, 0x1a, 0xfc, 0x89, 0xa8, 0xbd, 0x30, 0x27, 0xf3, 0xcf, 0x7e, 0x04, 0xb9, 0xb4, 0x0b, 0x24,
	0x41, 0xd3, 0xc0, 0x78, 0x8d, 0xd5, 0xcf, 0xd2, 0x9f, 0x1b, 0xbc, 0x35, 0xdf, 0xa9, 0x02, 0x02,
	0x68, 0x2d, 0xf1, 0xc2, 0xd4, 0xdf, 0xaa, 0x22, 0x52, 0xa0, 0x63, 0xae, 0x4d, 0xe3, 0xc3, 0xca,
	0xda, 0xa8, 0x8d, 0x99, 0x0e, 0x52, 0x71, 0xaa, 0xe8, 0x1c, 0xa4, 0xad, 0x79, 0x6b, 0xbc, 0x59,
	0x99, 0xc6, 0x6d, 0x46, 0xb0, 0x7c, 0xbf, 0xd6, 0x53, 0x82, 0x1e, 0xc8, 0x1b, 0xbc, 0x30, 0xad,
	0x85, 0xbe, 0x59, 0xad, 0x4d, 0x55, 0x44, 0x32, 0xb4, 0x17, 0xba, 0xbe, 0xde, 0x9a, 0x29, 0x89,
	0x0b, 0x83, 0x17, 0x4d, 0x86, 0xae, 0x60, 0xb0, 0x35, 0xad, 0xed, 0xd2, 0xd2, 0xf1, 0x6a, 0x69,
	0xec, 0xca, 0xe4, 0x43, 0xe8, 0x97, 0x43, 0xd6, 0x56, 0xd7, 0x0d, 0xcb, 0x52, 0x05, 0x74, 0x09,
	0xa8, 0x1c, 0x78, 0xb3, 0x58, 0xbd, 0x37, 0x6e, 0x55, 0x71, 0xfe, 0x07, 0x9c, 0xff, 0x9c, 0x38,
	0x71, 0xe2, 0x58, 0x24, 0x7a, 0xf0, 0x5d, 0x82, 0x66, 0x20, 0x15, 0x9a, 0xa8, 0xe6, 0xa6, 0x6b,
	0xa9, 0x40, 0xbe, 0x15, 0xd0, 0x4f, 0x20, 0x97, 0x3a, 0x44, 0x97, 0x95, 0x7b, 0x71, 0xa8, 0x19,
	0xd6, 0xf0, 0xec, 0xa2, 0x39, 0x2d, 0xfe, 0xf7, 0xf6, 0xfd, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x29, 0x0c, 0xab, 0xab, 0xff, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PubsubServiceClient is the client API for PubsubService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PubsubServiceClient interface {
	Subscribe(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (PubsubService_SubscribeClient, error)
	UnSubscribe(ctx context.Context, in *UnSubscribeRequest, opts ...grpc.CallOption) (*UnSubscribeResponse, error)
}

type pubsubServiceClient struct {
	cc *grpc.ClientConn
}

func NewPubsubServiceClient(cc *grpc.ClientConn) PubsubServiceClient {
	return &pubsubServiceClient{cc}
}

func (c *pubsubServiceClient) Subscribe(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (PubsubService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PubsubService_serviceDesc.Streams[0], "/pb.PubsubService/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &pubsubServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PubsubService_SubscribeClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type pubsubServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *pubsubServiceSubscribeClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *pubsubServiceClient) UnSubscribe(ctx context.Context, in *UnSubscribeRequest, opts ...grpc.CallOption) (*UnSubscribeResponse, error) {
	out := new(UnSubscribeResponse)
	err := c.cc.Invoke(ctx, "/pb.PubsubService/UnSubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PubsubServiceServer is the server API for PubsubService service.
type PubsubServiceServer interface {
	Subscribe(*EventRequest, PubsubService_SubscribeServer) error
	UnSubscribe(context.Context, *UnSubscribeRequest) (*UnSubscribeResponse, error)
}

func RegisterPubsubServiceServer(s *grpc.Server, srv PubsubServiceServer) {
	s.RegisterService(&_PubsubService_serviceDesc, srv)
}

func _PubsubService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PubsubServiceServer).Subscribe(m, &pubsubServiceSubscribeServer{stream})
}

type PubsubService_SubscribeServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type pubsubServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *pubsubServiceSubscribeServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _PubsubService_UnSubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnSubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PubsubServiceServer).UnSubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.PubsubService/UnSubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PubsubServiceServer).UnSubscribe(ctx, req.(*UnSubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PubsubService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.PubsubService",
	HandlerType: (*PubsubServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnSubscribe",
			Handler:    _PubsubService_UnSubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PubsubService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "event.proto",
}
